---
# GitLab OIDC Secret
# Namespace: gitlab
# Used by: GitLab OmniAuth for Keycloak SSO
# NOTE: Replace <CLIENT_SECRET> with actual value from Keycloak,
#       then seal with kubeseal for git persistence.
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-secret
  namespace: gitlab
type: Opaque
stringData:
  client-id: gitlab
  client-secret: PLACEHOLDER_RUN_SETUP_KEYCLOAK_REALM_SH
