---
# GitLab OmniAuth Provider Configuration
# Namespace: gitlab
# Used by: GitLab OmniAuth openid_connect strategy
# This secret contains the provider JSON that GitLab expects.
# NOTE: Replace <CLIENT_SECRET> with actual value from Keycloak,
#       then seal with kubeseal for git persistence.
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-provider
  namespace: gitlab
type: Opaque
stringData:
  provider: |
    {
      "name": "openid_connect",
      "label": "Keycloak",
      "args": {
        "name": "openid_connect",
        "scope": ["openid", "profile", "email"],
        "response_type": "code",
        "issuer": "https://auth.vectorweight.com/realms/vectorweight",
        "discovery": true,
        "client_auth_method": "query",
        "uid_field": "preferred_username",
        "client_options": {
          "identifier": "gitlab",
          "secret": "PLACEHOLDER_RUN_SETUP_KEYCLOAK_REALM_SH",
          "redirect_uri": "https://git.vectorweight.com/users/auth/openid_connect/callback"
        }
      }
    }
