---
# Grafana OIDC Secret
# Namespace: monitoring
# Used by: Grafana (via envFromSecret) for Keycloak SSO
# The key GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET is the Grafana env var convention.
# NOTE: Replace <CLIENT_SECRET> with actual value from Keycloak,
#       then seal with kubeseal for git persistence.
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: PLACEHOLDER_RUN_SETUP_KEYCLOAK_REALM_SH
