---
# Open WebUI OIDC Secret
# Namespace: ai-services
# Used by: Open WebUI deployment for Keycloak SSO
# NOTE: Replace <CLIENT_SECRET> with actual value from Keycloak,
#       then seal with kubeseal for git persistence.
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oidc-secret
  namespace: ai-services
type: Opaque
stringData:
  client-id: open-webui
  client-secret: PLACEHOLDER_RUN_SETUP_KEYCLOAK_REALM_SH
