# Longhorn RecurringJob: daily-snapshot
# Takes daily snapshots at 2 AM, retains 7 days
#
# NOTE: Only snapshot jobs here. Backup jobs require a configured backup target
# (S3 or NFS). Adding backup jobs without a target causes Longhorn controller errors.
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: {{ .Values.recurringJobs.dailySnapshot.name }}
  namespace: longhorn-system
  labels:
    {{- include "longhorn-config.labels" . | nindent 4 }}
    {{- with .Values.recurringJobs.dailySnapshot.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  cron: {{ .Values.recurringJobs.dailySnapshot.cron | quote }}
  task: {{ .Values.recurringJobs.dailySnapshot.task }}
  retain: {{ .Values.recurringJobs.dailySnapshot.retain }}
  concurrency: {{ .Values.recurringJobs.dailySnapshot.concurrency }}
  groups:
    - default
