# Longhorn StorageClass: longhorn-homelab (default)
# Single replica with best-effort data locality for homelab workloads
#
# IMPORTANT: Do NOT include 'fromBackup' parameter — even an empty string
# triggers Longhorn v1.10.x webhook validation that requires a backup target,
# creating a deadlock where volumes can't provision or be patched.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.homelab.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageClasses.homelab.isDefault }}"
  labels:
    {{- include "longhorn-config.labels" . | nindent 4 }}
parameters:
  numberOfReplicas: "{{ .Values.storageClasses.homelab.numberOfReplicas }}"
  dataLocality: {{ .Values.storageClasses.homelab.dataLocality }}
  fsType: {{ .Values.storageClasses.homelab.fsType }}
  staleReplicaTimeout: "{{ .Values.storageClasses.homelab.staleReplicaTimeout | default 30 }}"
  {{- if .Values.storageClasses.homelab.nodeSelector }}
  nodeSelector: {{ .Values.storageClasses.homelab.nodeSelector }}
  {{- end }}
provisioner: driver.longhorn.io
reclaimPolicy: {{ .Values.storageClasses.homelab.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.storageClasses.homelab.allowVolumeExpansion }}
---
# Longhorn StorageClass: longhorn-gpu-local
# Single replica with strict-local data locality for GPU workloads
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.gpuLocal.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageClasses.gpuLocal.isDefault }}"
  labels:
    {{- include "longhorn-config.labels" . | nindent 4 }}
parameters:
  numberOfReplicas: "{{ .Values.storageClasses.gpuLocal.numberOfReplicas }}"
  dataLocality: {{ .Values.storageClasses.gpuLocal.dataLocality }}
  fsType: {{ .Values.storageClasses.gpuLocal.fsType }}
  staleReplicaTimeout: "{{ .Values.storageClasses.gpuLocal.staleReplicaTimeout | default 30 }}"
provisioner: driver.longhorn.io
reclaimPolicy: {{ .Values.storageClasses.gpuLocal.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.storageClasses.gpuLocal.allowVolumeExpansion }}
