# Actions Runner Controller (ARC) - Controller
# GitHub Actions self-hosted runner controller
# Ref: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"  # Deploy in CI/CD tier
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # ARC chart 0.9.3 ClusterRole lacks patch/update on serviceaccounts,
  # which the controller needs for finalizer management in runner namespaces.
  # We manually add these verbs; ignoreDifferences prevents selfHeal from reverting.
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.9.3
    helm:
      skipCrds: true  # CRDs managed manually to avoid annotation size issues
      valuesObject:
        # Resource limits for controller
        replicaCount: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        # Security context for Kyverno pod-security-baseline compliance
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL

        # Metrics for monitoring
        metrics:
          controllerManagerAddr: ":8080"
          listenerAddr: ":8080"
          listenerEndpoint: "/metrics"

        # Pin to homelab node
        nodeSelector:
          kubernetes.io/hostname: homelab

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Avoid annotation size limit issues
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
