apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy first - required for GPU workloads
spec:
  project: default
  source:
    # Repository: https://helm.ngc.nvidia.com/nvidia (official NVIDIA GPU Operator)
    # Version: v25.10.1 (latest with RTX 5080 support and time-slicing)
    chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v25.10.1
    helm:
      values: |
        # NVIDIA GPU Operator for RTX 5080 with Time-Slicing
        # Chart: nvidia/gpu-operator
        # Version: 25.10.x
        # Target Hardware: RTX 5080 (16GB GDDR7 VRAM, Blackwell architecture)
        #
        # Configuration Rationale:
        # - Driver installation enabled for RTX 5080 compatibility
        # - Time-slicing enabled to share GPU across multiple workloads
        # - MIG disabled (not supported on RTX 5080)
        # - Containerd runtime configured for k3s compatibility

        driver:
          enabled: true  # Required for RTX 5080 - installs NVIDIA drivers on host

        toolkit:
          enabled: true
          env:
            - name: CONTAINERD_CONFIG
              value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
            - name: CONTAINERD_SOCKET
              value: /run/k3s/containerd/containerd.sock

        devicePlugin:
          enabled: true

        dcgmExporter:
          enabled: true

        gfd:
          enabled: true

        migManager:
          enabled: false  # RTX 5080 does not support MIG (Multi-Instance GPU)

        validator:
          enabled: true
          env:
            - name: WITH_WORKLOAD
              value: "true"

        cdi:
          enabled: true
          default: true

        # Time-slicing configuration for 4 virtual GPUs
        operator:
          defaultRuntime: containerd

        devicePlugin:
          config:
            name: time-slicing-config
            create: false
            default: rtx-5080
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
