# Kyverno Policy Engine
# Provides admission control and policy enforcement for the cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Kyverno Helm chart
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.3.3
      helm:
        valuesObject:
          # Single replica for homelab
          replicaCount: 1

          # Resource limits
          admissionController:
            replicas: 1
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

          backgroundController:
            replicas: 1
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi

          cleanupController:
            replicas: 1
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi

          reportsController:
            replicas: 1
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi

          # Enable policy reports
          features:
            policyReports:
              enabled: true
            logging:
              format: json

    # Source 2: Custom policies from local directory
    - repoURL: https://github.com/tzervas/self-hosted-ai.git
      targetRevision: dev
      path: policies/kyverno

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
