# Longhorn Storage System
# ArgoCD Application for distributed block storage
#
# Prerequisites:
#   - btrfs subvolume at /var/lib/longhorn on each node
#   - Mount options: subvol=@longhorn,noatime,compress=zstd:1,space_cache=v2,discard=async
#
# This application:
#   1. Installs Longhorn operator from official Helm chart
#   2. Configures custom StorageClasses (longhorn-homelab, longhorn-gpu-local)
#   3. Sets up recurring snapshot jobs (daily/weekly)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Official Longhorn Helm chart
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.7.2
      helm:
        valuesObject:
          # Default settings for homelab
          defaultSettings:
            defaultReplicaCount: 2
            defaultDataLocality: best-effort
            defaultDataPath: /var/lib/longhorn
            storageMinimalAvailablePercentage: 10
            storageReservedPercentageForDefaultDisk: 15
            # Disable automatic deletion of snapshots on volume deletion
            autoDeletePodWhenVolumeDetachedUnexpectedly: true
            # Node drain policy
            nodeDrainPolicy: block-for-eviction

          # Ingress for Longhorn UI (accessible via Traefik)
          ingress:
            enabled: true
            ingressClassName: traefik
            host: longhorn.homelab.local
            tls: false

          # Resource limits for Longhorn components
          longhornManager:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

          longhornDriver:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi

    # Source 2: Custom StorageClasses and RecurringJobs from local chart
    - repoURL: https://github.com/tzervas/self-hosted-ai.git
      targetRevision: dev
      path: infrastructure/longhorn

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
