# Longhorn Storage System
# ArgoCD Application for distributed block storage
#
# Prerequisites:
#   - /data/longhorn directory on each node (mounted on large data partition)
#   - For homelab: single-node setup uses /data (3TB btrfs) for Longhorn storage
#
# This application:
#   1. Installs Longhorn operator from official Helm chart
#   2. Configures custom StorageClasses (longhorn-homelab, longhorn-gpu-local)
#   3. Sets up recurring snapshot jobs (daily/weekly)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Official Longhorn Helm chart
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.7.2
      helm:
        # Skip hooks for fresh installs (pre-upgrade hook fails without existing resources)
        skipCrds: false
        valuesObject:
          # Default settings for homelab (single-node, data on /data partition)
          defaultSettings:
            defaultReplicaCount: 1
            defaultDataLocality: best-effort
            defaultDataPath: /data/longhorn
            storageMinimalAvailablePercentage: 10
            storageReservedPercentageForDefaultDisk: 15
            # Disable automatic deletion of snapshots on volume deletion
            autoDeletePodWhenVolumeDetachedUnexpectedly: true
            # Node drain policy
            nodeDrainPolicy: block-for-eviction

          # Ingress for Longhorn UI (accessible via Traefik, behind Keycloak)
          ingress:
            enabled: true
            ingressClassName: traefik
            host: longhorn.vectorweight.com
            tls: true
            tlsSecret: vectorweight-wildcard-tls
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.middlewares: automation-longhorn-forward-auth@kubernetescrd

          # Resource limits for Longhorn components
          longhornManager:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

          longhornDriver:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi

    # Source 2: Custom StorageClasses and RecurringJobs from local chart
    - repoURL: https://github.com/tzervas/self-hosted-ai.git
      targetRevision: main
      path: infrastructure/longhorn

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      # Skip pre-upgrade hooks (only needed for upgrades, not fresh installs)
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
