# Longhorn Storage System
# ArgoCD Application for distributed block storage
#
# Prerequisites:
#   - /data/longhorn directory on homelab node (3TB volume)
#   - For homelab: Uses /data/longhorn for Longhorn storage
#
# This application:
#   1. Installs Longhorn operator from official Helm chart
#   2. Configures custom StorageClasses (longhorn-homelab, longhorn-gpu-local)
#   3. Sets up recurring snapshot jobs (daily/weekly)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    # Longhorn operator mutates CRDs at runtime (adds versions, labels, annotations).
    # Ignore these fields to prevent perpetual OutOfSync.
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.versions
        - .metadata.labels
        - .metadata.annotations
  sources:
    # Source 1: Official Longhorn Helm chart
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.10.1
      helm:
        # Skip hooks for fresh installs (pre-upgrade hook fails without existing resources)
        skipCrds: false
        valuesObject:
          # Default settings for homelab (single-node, data on /data partition)
          defaultSettings:
            defaultReplicaCount: 1
            defaultDataLocality: best-effort
            defaultDataPath: /data/longhorn
            storageMinimalAvailablePercentage: 10
            storageReservedPercentageForDefaultDisk: 15
            autoDeletePodWhenVolumeDetachedUnexpectedly: true
            nodeDrainPolicy: block-for-eviction
            # IMPORTANT: Do not set backupTarget without a valid URL.
            # Empty backup targets cause v1.10.x webhook deadlocks.

          # Override the auto-created 'longhorn' StorageClass defaults
          # Without this, the chart creates a 'longhorn' SC with numberOfReplicas=3
          # which is impossible on a single-node cluster.
          persistence:
            defaultClass: false  # Let longhorn-homelab be the default
            defaultClassReplicaCount: 1
            defaultDataLocality: best-effort

          # Ingress for Longhorn UI (accessible via Traefik, behind Keycloak)
          ingress:
            enabled: true
            ingressClassName: traefik
            host: longhorn.vectorweight.com
            tls: true
            tlsSecret: vectorweight-wildcard-tls
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.middlewares: automation-longhorn-forward-auth@kubernetescrd

          # Resource limits for Longhorn components
          longhornManager:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

          longhornDriver:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi

    # Source 2: Custom StorageClasses and RecurringJobs from local chart
    - repoURL: https://github.com/tzervas/self-hosted-ai.git
      targetRevision: main
      path: infrastructure/longhorn

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      # Skip pre-upgrade hooks (only needed for upgrades, not fresh installs)
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
