apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # Deploy after databases
spec:
  project: default
  source:
    chart: n8n
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 0.26.1
    helm:
      values: |
        image:
          repository: n8nio/n8n
          tag: 2.4.0
          pullPolicy: IfNotPresent
        
        service:
          type: ClusterIP
          port: 5678
        
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: n8n.homelab.local
              paths:
                - path: /
                  pathType: Prefix
        
        env:
          # Core settings
          N8N_HOST: "0.0.0.0"
          N8N_PORT: "5678"
          N8N_PROTOCOL: "https"
          GENERIC_TIMEZONE: "America/New_York"
          
          # Execution settings
          EXECUTIONS_PROCESS: "main"
          EXECUTIONS_DATA_PRUNE: "true"
          EXECUTIONS_DATA_MAX_AGE: "168"
          
          # Binary data (filesystem for large files)
          N8N_DEFAULT_BINARY_DATA_MODE: "filesystem"
          N8N_BINARY_DATA_STORAGE_PATH: "/home/node/.n8n/binary-data"
        
        # Secret environment variables
        envFromSecrets:
          - name: n8n-secret
            key: N8N_ENCRYPTION_KEY
            env: N8N_ENCRYPTION_KEY
          - name: n8n-secret
            key: N8N_BASIC_AUTH_USER
            env: N8N_BASIC_AUTH_USER
          - name: n8n-secret
            key: N8N_BASIC_AUTH_PASSWORD
            env: N8N_BASIC_AUTH_PASSWORD
        
        persistence:
          enabled: true
          size: 10Gi
          storageClass: ""
        
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 4Gi
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 60
          periodSeconds: 30
        
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
