apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # Deploy after GPU operator (wave 3)
spec:
  project: default
  source:
    # Repository: https://otwld.github.io/helm-charts (migrated from helm.otwld.com)
    # Version: 1.37.0 (latest with GPU support and security improvements)
    chart: ollama
    repoURL: https://otwld.github.io/helm-charts
    targetRevision: 1.37.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
