apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # Deploy after inference services
spec:
  project: default
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com
    targetRevision: 3.5.2
    helm:
      values: |
        replicaCount: 1
        image:
          repository: ghcr.io/open-webui/open-webui
          tag: v0.8.5
          pullPolicy: IfNotPresent
        
        service:
          type: ClusterIP
          port: 8080
        
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: ai.homelab.local
              paths:
                - path: /
                  pathType: Prefix
        
        # Environment configuration
        env:
          - name: OLLAMA_BASE_URLS
            value: "http://ollama:11434;http://gpu-worker-ollama.gpu-worker:11434"
          - name: WEBUI_NAME
            value: "Self-Hosted AI Server"
          - name: WEBUI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: webui-secret
                key: secret-key
          - name: WEBUI_ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: webui-secret
                key: admin-email
          - name: WEBUI_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webui-secret
                key: admin-password
          - name: WEBUI_ADMIN_NAME
            value: "Administrator"
          # CRITICAL: Force env vars to override database
          - name: ENABLE_PERSISTENT_CONFIG
            value: "False"
          - name: ENABLE_AUTH
            value: "true"
          - name: ENABLE_SIGNUP
            value: "false"
          # SearXNG web search
          - name: ENABLE_RAG_WEB_SEARCH
            value: "true"
          - name: RAG_WEB_SEARCH_ENGINE
            value: "searxng"
          - name: SEARXNG_QUERY_URL
            value: "http://searxng:8080/search?q=<query>"
          - name: RAG_WEB_SEARCH_RESULT_COUNT
            value: "3"
          # Image generation
          - name: ENABLE_IMAGE_GENERATION
            value: "true"
          - name: IMAGE_GENERATION_ENGINE
            value: "comfyui"
          - name: COMFYUI_BASE_URL
            value: "http://comfyui.gpu-worker:8188"
        
        persistence:
          enabled: true
          size: 20Gi
          storageClass: ""
        
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
