apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy early - database tier
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.32
    helm:
      values: |
        auth:
          existingSecret: postgresql-secret
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
          database: litellm
          username: litellm
        image:
          tag: 16.4.0-debian-12-r12
        primary:
          persistence:
            enabled: true
            size: 20Gi
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          extendedConfiguration: |
            shared_preload_libraries = 'pg_stat_statements'
            pg_stat_statements.track = all
        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
