# QEMU binfmt DaemonSet
# Registers QEMU binary format handlers for multi-arch emulation
#
# This enables running ARM64, ARM, RISC-V, and other architectures
# on amd64 nodes via transparent QEMU user-mode emulation.
#
# Required for:
#   - ARM64 CI runners (emulated)
#   - Multi-arch Docker builds via buildx
#   - Cross-compilation testing

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qemu-binfmt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Early - needed by other workloads
  labels:
    app.kubernetes.io/component: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tzervas/self-hosted-ai.git
    targetRevision: dev
    path: helm/qemu-binfmt
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
