apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy early - database tier
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.6.4
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: true
          existingSecret: redis-secret
          existingSecretPasswordKey: redis-password
        image:
          tag: 7.2.5-debian-12-r0
        master:
          persistence:
            enabled: true
            size: 8Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
