# TTS Server - Text to Speech
# DISABLED: Coqui AI shut down in December 2023 and their model CDN
# (coqui.gateway.scarf.sh) is permanently offline. The container crashes
# on startup trying to download models.
#
# TODO: Replace with Piper TTS (actively maintained, CPU-efficient)
#   Image: lscr.io/linuxserver/piper:latest
#   See: https://github.com/rhasspy/piper
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tts-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/tzervas/self-hosted-ai.git
    targetRevision: main
    path: helm/gpu-worker
    helm:
      releaseName: tts-server
      values: |
        # All components disabled until Piper TTS replacement is ready
        ollama:
          gpu:
            enabled: false
        comfyui:
          enabled: false
        automatic1111:
          enabled: false
        audio:
          enabled: false
        video:
          enabled: false
        tts:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
