# App-of-Apps Root Application
# This application manages all child applications in the cluster
# Sync waves ensure proper deployment order:
#   -2: Secret infrastructure (SealedSecrets)
#   -1: Storage infrastructure (Longhorn)
#    0: Databases (PostgreSQL, Redis)
#    1: GPU infrastructure (GPU Operator, Traefik)
#    2: Policy enforcement (Kyverno)
#    3: Monitoring stack (Prometheus, Grafana)
#    4: Source control (GitLab)
#    5: AI inference (Ollama, LiteLLM)
#    6: User-facing applications (Open WebUI, n8n, SearXNG)
#    7: CI/CD runners (ARC, GitLab Runner)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tzervas/self-hosted-ai.git
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: false
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      # CRITICAL: Never auto-prune the root app to prevent accidental deletion
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
